### PR TITLE
Added ability to check connectivity regularly

### PR DESCRIPTION
**Pull request by adrienthiery**
Hi there @rauliyohmc !

Thanks for the awesome lib. Super helpful.

I noticed an issue in my case, though. 
It is that is check the connectivity only at startup, so I added an option so it checks regularly for connection and by default, it keeps the exact same behaviour that you had.

What do you think ? 🙂

### CODE REVIEW

**Comment by rauliyohmc** [comment]
Hi @adrienthiery, thanks for the PR.

I am trying to understand the use case. Since the listener will trigger any time the connection changes, what's the point on checking connectivity regularly? Could you maybe elaborate better with an example?

**Comment by adrienthiery** [comment]
Hi @rauliyohmc,

My main use-case is when I use a custom pingUrl for it to ping my server. 
For example, if my server is down for some reason (maintenance, etc.), I'd like for the clients to act as if they were offline, instead of handling it as an error.

**Comment by adrienthiery** [comment]
It also means it does an effective check if connectivity to my server so if the connection is bad but I'm still on the network, then my app shows up as offline. That's the behaviour that I want

**Comment by rauliyohmc** [comment]
If you server is down for some reason and you'd like the clients to act as if they were offline, I think you can easily do that (assuming you are using `redux`).

Just import the internal action creator, catch the server error and dispatch yourself the action to state offline mode.

```js
import { offlineActionTypes } from 'react-native-offline';
...
fetch(`${YOUR_SERVER_ENDPOINT}`)
  .then(response => // do something)
  .catch(error => dispatch({ type: offlineActionTypes.CONNECTION_CHANGE, payload: false }))
```

**Comment by adrienthiery** [comment]
@rauliyohmc I could do that, but then I would need to recreate the same structure you have in redux-offline to get a singleton of an interval checking regularly the connectivity, and I thought some other people might want this feature as well, it's really awesome to have my app bound to the "state" of my server almost instantly.

**Comment by rauliyohmc** [comment]
I saw you are a speaker of the React Native EU conference coming next week. I'll be there giving a workshop and attending the talks as well, so we can discuss further in person :)

I would like to prioritise [this PR first](https://github.com/rauliyohmc/react-native-offline/pull/29) (see both comments), mainly to decouple the redux part from the higher order component and create an event emitter/subscriber system that will work for all cases.

I am also thinking we could add support for websockets if you use a custom server. That way we can move from polling to server push notifications.

**Comment by adrienthiery** [comment]
Sounds good! 🙂

**Comment by raduflp** [comment]
I would love to see this merged. 
Another argument would be that sometimes it takes a while for the underlying OS to update the internet connection status, so regular checks would make the app more responsive.

**Comment by kraffslol** [comment]
I agree with @raduflp. I have some issues on android devices where they can't pick up internet connection fast enough. The fetch call in [checkInternetAccess.js](https://github.com/rauliyohmc/react-native-offline/blob/master/src/checkInternetAccess.js) instantly throws and returns false. This would be great if it needs to retry.

**Comment by rauliyohmc** [comment]
Hey @adrienthiery, since this people would find this useful and it's opt-in feature, let's merge it :)

Could you please rebase and address the conflicts?

**Comment by ValentinBlokhin** [comment]
Have the same issue. When I connected to wifi but no internet, there is no way to handle connection change when connection online after some time.

**Comment by adrienthiery** [comment]
Hi @rauliyohmc,

Will do during the day!

**Comment by TyshkevichSergey** [comment]
Would be great to see this feature merged. Will be very helpful for a lot of people.

**Comment by adrienthiery** [comment]
@rauliyohmc : There you go 😄

**Pull request merged**
